/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GamesPanelUI.java
 *
 * Created on 16 Dec, 2009, 9:14:55 PM
 */

package c.UI;

/**
 *
 * @author Suhas Bharadwaj
 */
public class GamesPanelUI extends javax.swing.JPanel {

    public int gameNumber = 1;
     ChessBoardUI njf = null;
    /** Creates new form GamesPanelUI */
    public GamesPanelUI(ChessBoardUI n) {
        njf = n;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butFirstGame = new javax.swing.JButton();
        butPrevGame = new javax.swing.JButton();
        butNextGame = new javax.swing.JButton();
        butLastGame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labGameNo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labWhitePlayerName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labBlackPlayerName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labGameResult = new javax.swing.JLabel();
        butBrowseGames = new javax.swing.JButton();

        butFirstGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start.gif"))); // NOI18N
        butFirstGame.setToolTipText("First Game");
        butFirstGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butFirstGameActionPerformed(evt);
            }
        });

        butPrevGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/prev.gif"))); // NOI18N
        butPrevGame.setToolTipText("Previous Game");

        butNextGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.gif"))); // NOI18N
        butNextGame.setToolTipText("Next Game");

        butLastGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/end.gif"))); // NOI18N
        butLastGame.setToolTipText("Last Game");

        jLabel1.setText("Game No.   : ");

        labGameNo.setText("1");

        jLabel3.setText("White         : ");

        labWhitePlayerName.setText("Suhas");

        jLabel5.setText("Black          : ");

        labBlackPlayerName.setText("Player1");

        jLabel7.setText("Result        : ");

        labGameResult.setText("1/2-1/2");

        butBrowseGames.setText("....");
        butBrowseGames.setToolTipText("Browse Games");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labGameNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(butBrowseGames, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labGameResult)
                            .addComponent(labBlackPlayerName)
                            .addComponent(labWhitePlayerName)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butFirstGame, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butPrevGame, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butNextGame, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butLastGame, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labGameNo)
                    .addComponent(butBrowseGames, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labWhitePlayerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labBlackPlayerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labGameResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butLastGame, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(butNextGame, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butPrevGame, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butFirstGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butFirstGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butFirstGameActionPerformed
        // TODO add your handling code here:
        njf.currentGameNo = 1;
        njf.setEachPGNGame(njf.currentGameNo);
    }//GEN-LAST:event_butFirstGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBrowseGames;
    private javax.swing.JButton butFirstGame;
    private javax.swing.JButton butLastGame;
    private javax.swing.JButton butNextGame;
    private javax.swing.JButton butPrevGame;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labBlackPlayerName;
    private javax.swing.JLabel labGameNo;
    private javax.swing.JLabel labGameResult;
    private javax.swing.JLabel labWhitePlayerName;
    // End of variables declaration//GEN-END:variables

}
